# Generated by Django 2.2.16 on 2021-12-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_cart_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
    ]
